import './globals.css'
import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <header>
          <ul>
            <li><Link href="/" className='home-button'></Link></li>
            <li><Link href="/your_post" className='user-button'></Link></li>
            <li><Link href="/login" className='login-button'>ログイン</Link></li>
          </ul>
        </header>
        <div className='children'>{children}</div>
      </body>
    </html>
  )
}
